name: Deploy FastAPI

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs GitHub Actions on a virtual machine
    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/african-knowledge-ai
            
            # Check for modified files and stash them
            if [[ -n "$(git status --porcelain)" ]]; then
              git stash
            fi
            
            # Pull latest changes from main branch
            git pull origin main
            
            # Activate virtual environment
            source venv/bin/activate
            
            # Install dependencies
            pip install -r backend/requirements.txt
            
            # Restart FastAPI service
            sudo supervisorctl restart fastapi
